import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import LoginBtn, { LogOutBtn, RegBtn } from "@/app/sign/SignBtn";
import { getServerSession } from "next-auth";
import { GET } from "../app/api/auth/[...nextauth]/route";
import AuthSession from "@/AuthSession";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(GET);
  console.log("session", session);

  return (
    <html lang="en">
      <body>
        <AuthSession>
          <div className="navbar">
            <div className="navbar-links">
              <Link href="/" className="logo">
                <Image
                  src="/image/logo.png"
                  alt="시크릿톡 로고"
                  width={100}
                  height={50}
                />
              </Link>
            </div>
            <div className="navbar-right">
              <Link href="/send-letter" className="send-letter">
                편지 보내기
              </Link>
              <Link href="/mailbox" className="mailbox">
                편지함
              </Link>
              |{/* 로그인/로그아웃 버튼 */}
              {session ? (
                <LogOutBtn />
              ) : (
                <div>
                  <LoginBtn /> <RegBtn />
                </div>
              )}
            </div>
          </div>
          {children}
        </AuthSession>
      </body>
    </html>
  );
}
